name: Publish to NPM

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org/'

      - name: Install Dependencies
        run: npm ci

      - name: Build Package
        run: npm run build

      - name: Determine Version Bump
        id: check_prefix
        run: |
          TITLE=$(git log -1 --pretty=%B)
          if [[ "$TITLE" =~ ^(change): ]]; then
            echo "VERSION_BUMP=major" >> $GITHUB_ENV
          elif [[ "$TITLE" =~ ^(add): ]]; then
            echo "VERSION_BUMP=minor" >> $GITHUB_ENV
          elif [[ "$TITLE" =~ ^(fix): ]]; then
            echo "VERSION_BUMP=patch" >> $GITHUB_ENV
          else
            echo "VERSION_BUMP=skip" >> $GITHUB_ENV
          fi

      - name: Bump Version
        if: env.VERSION_BUMP != 'skip'
        run: npm version $VERSION_BUMP --no-git-tag-version

      - name: Publish to NPM
        if: env.VERSION_BUMP != 'skip'
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Push New Version Tag
        if: env.VERSION_BUMP != 'skip'
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git tag v$(node -p "require('./package.json').version")
          git push origin v$(node -p "require('./package.json').version")
